version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: mysql84
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_0900_ai_ci"]
    volumes:
      - ./dbdata:/var/lib/mysql
