name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test Backend
      working-directory: demo
      run: |
        chmod +x mvnw
        ./mvnw -B -Psecurity verify
        
    - name: Build and Test Frontend
      working-directory: frontend
      run: |
        chmod +x mvnw
        ./mvnw -B -Psecurity verify

    # Subir reportes como artefactos
    - name: Upload Test and Security Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-and-security-reports
        path: |
          demo/target/surefire-reports/
          demo/target/dependency-check-report.html
          frontend/target/surefire-reports/
          frontend/target/dependency-check-report.html
        retention-days: 7